############################################################
# input files

model_file: './M87_230GHz_Chael.fits'

############################################################
# observation specs

source: 'M87'       # name of science target
RA: 12.51373        # right ascension of science target, in J2000 hours
DEC: 12.39112       # declination of science target, in J2000 degrees
frequency: '230'    # observing frequency, in GHz; options are 86, 230, 345
bandwidth: 2.0      # fringe-finding bandwidth, in GHz
nbands: 1           # number of bands
rf_offset: 0.0      # rf offset, in GHz; should be larger than bandwidth for nbands > 1

day: '15'           # day of the month for the observation
month: 'Apr'        # month of observation; uses three-letter abbreviations
year: '2025'        # year of observation

t_start: 0.         # start time of observation, in hours
dt: 24.             # total duration of observation, in hours
t_int: 300.         # integration time, in seconds
t_rest: 600.        # time interval between consecutive integrations, in seconds

# SNR thresholding scheme; options are:
# ['naive',threshold]
# ['fringegroups', [strong baseline SNR threshold, strong baseline coherence time (in seconds)]
# ['fpt', [strong baseline SNR threshold, strong baseline coherence time (in seconds), FPT reference frequency (in GHz), path to FPT reference model]
SNR_cutoff: ['fringegroups', [5., 10.]]

############################################################
# array specs

D_new: 10.          # new dish diameter, in meters
tech_readiness: 1.0 # derating for technical readiness

# list containing the array site names
sites: ['ALMA', 'APEX', 'GLT', 'IRAM', 'JCMT', 'KP', 'LMT', 'NOEMA', 'SMA', 'SMT', 'SPT', 'BAJA', 'BAR', 'CNI', 'HAY', 'LAS', 'OVRO']

############################################################
# other settings

ttype: 'fast'                   # type of Fourier transform ('direct', 'nfft', or 'fast')
fft_pad_factor: 2               # zero pad the image to fft_pad_factor * image size in the FFT
random_seed: 12345              # random number seed; if blank, will be auto-generated
