############################################################
# input files

model_file: './example_script/M87_230GHz_Chael.fits'
path_to_weather: './utils/weather_data/'

############################################################
# observation specs

source: 'M87'       # name of science target
frequency: '230'    # observing frequency, in GHz; options are 86, 230, 345
bandwidth: 8.0      # fringe-finding bandwidth, in GHz
nbands: 1           # number of bands
rf_offset: 0.0      # rf offset, in GHz; should be larger than bandwidth for nbands > 1

month: 'Apr'        # month of observation; uses three-letter abbreviations
year: '2025'        # year of observation

t_start: 0.         # start time of observation, in hours
dt: 24.             # total duration of observation, in hours
t_int: 300.         # integration time, in seconds
t_rest: 900.       # time interval between consecutive integrations, in seconds

# SNR thresholding scheme
# options are ['naive',threshold]; or
# ['adhoc',[reference station threshold, reference station tint, non-reference station threshold, backup threshold SNR on t_int]]; or
# ['fringegroups', [strong baseline SNR threshold, strong baseline coherence time (in seconds)]
# SNR_cutoff: ['adhoc', [10., 10., 3., 10.]]
SNR_cutoff: ['fringegroups', [5., 10.]]

############################################################
# array specs

D_new: 8.          # new dish diameter, in meters
tech_readiness: 1.0 # derating for technical readiness
RMS_point_err: 2.   # RMS pointinng error at the new sites, in arcseconds
ref_station: 'ALMA' # reference station for ad hoc phasing

# list containing the array site names
sites: ['BAJA','CNI','HAY','LAS','OVRO','ALMA','APEX','JCMT','LMT','IRAM','SMA','SMT','SPT','KP','NOEMA','GLT','GARS','GAM','CAT','BOL','BRZ','PIKE']

############################################################
# other settings

ttype: 'fast'                   # type of Fourier transform ('direct', 'nfft', or 'fast')
weather_randomness: 'random'    # can be 'random' or 'mean'
random_seed: 1                   # random number seed; if blank, will be auto-generated
